export const FETCH_POKEMON_LIST = "FETCH_POKEMON_LIST";
export const FETCH_POKEMON_LIST_SUCCESS = "FETCH_POKEMON_LIST_SUCCESS";
export const FETCH_POKEMON_LIST_FAILED = "FETCH_POKEMON_LIST_FAILED";

export const SELECT_POKEMON = "SELECT_POKEMON";

export const FETCH_POKEMON_DETAILS = "FETCH_POKEMON_DETAILS";
export const FETCH_POKEMON_DETAILS_SUCCESS = "FETCH_POKEMON_DETAILS_SUCCESS";
export const FETCH_POKEMON_DETAILS_FAILED = "FETCH_POKEMON_DETAILS_FAILED";

export const FETCH_POKEMON_DESCRIPTION = "FETCH_POKEMON_DESCRIPTION";
export const FETCH_POKEMON_DESCRIPTION_SUCCESS = "FETCH_POKEMON_DESCRIPTION_SUCCESS";
export const FETCH_POKEMON_DESCRIPTION_FAILED = "FETCH_POKEMON_DESCRIPTION_FAILED";